config/routes.rb
Rails.application.routes.draw do
  get 'tags/create'
  root to: 'homes#toppage'
  devise_for :users
  resources :link_tags
  resources :tags
  resources :links
  resources :users
  post 'users/:id/edit' => 'users#update'
  post 'tags/first_create' => 'tags#first_create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/link.rb
class Link < ApplicationRecord
     belongs_to :user
     has_many :link_tags
     
     validates :title, presence: true
     validates :url, presence: true
     
end

app/models/link_tag.rb
class LinkTag < ApplicationRecord
    belongs_to :link
    belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :link_tags
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable       
  has_many :links, dependent: :destroy
  has_many :tags
  has_one_attached :image

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!, except: [:top]
    before_action :configure_permitted_parameters, if: :devise_controller?
    before_action :authenticate_user!
    before_action :set_host

    def after_sign_up_path_for(resource)
      tags_first_create_path(resource)
    end
    
    def after_sign_in_path_for(resource)
      links_path
    end
    
     private

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up,keys:[:email]) # 注目
    end
    
    def set_host
      Rails.application.routes.default_url_options[:host] = request.host_with_port
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
    def toppage
    end    
end

app/controllers/link_tags_controller.rb
class LinkTagsController < ApplicationController
  def create
    @link = Link.find(params[:id])
    linktag = current_user.linktags.new(link_id: @link.id)
    linktag.save
    render :link
  end

  def destroy
    @link = Link.find(params[:id])
    linktag = current_user.linktags.new(link_id: @link.id)
    linktag.destroy
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController


    def new
      @link = Link.new
      @linktag = LinkTag.new
      @linktags = LinkTag.all
      @tag = Tag.new #タグをユーザーに持たせるか
      @tags = Tag.where(user_id: current_user)
     if params[:tag]
      Tag.create(name: params[:tag])
     end
    end
    
    def create
      @link = Link.new(link_params)
      @link.user_id = current_user.id
      if @link.save
      redirect_to links_path
      else
      render :new
      end
    end
    
    def edit
       @link = Link.find(params[:id])
    end
    
    def update
      @link = Link.find(params[:id])
      @link.user_id = current_user.id
      if @link.update(link_params)
      redirect_to links_path
      else
      render :edit
      end
    end
    
    def index
       @links = Link.all.where(user_id: current_user)
    end
    
    def destroy
       link=Link.find(params[:id])
       link.destroy
       redirect_to links_path
    end 
    
  private

    def link_params
      params.require(:link).permit(:title,:url,:body,:color)
    end

    
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def create
    @tag = Tag.new(tag_params)
    @tag.save
  end

  def first_create(resourse)
    @tag = Tag.new(user_id: resource.id,name: "all")
    @tag.save
    redirect_to links_path
  end

  private
  def tag_params
    params.require(:tag).permit(:name)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def index 
      @user = User.find(params[:id])
      @userinfo = current_user.id
    end

    def edit
      @user = User.find(params[:id])
    end

    def update
    user = User.find(params[:id])
    user.update(user_params)
    redirect_to user_path(user.id)  
    end

private
  def user_params
    params.require(:user).permit(:name, :email, :image)  
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/link_tags_helper.rb
module LinkTagsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/links/_form.html.erb
<link rel="stylesheet" href="/assets/new_form.scss"/>
<div class="form">
  
 
  <% if @link.errors.any? %>
  <div class="error">
  <%= @link.errors.count %>件のエラーが発生しました
  <ul>
    <% @link.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
  </div>
<% end %>

<%= form_with model:@link, local:true do |f| %>
<ul>
  <li class="name"><%= f.label :name, 'タイトル' %></li>
  <li><%= f.text_field :title, class: "hoge", size: "60x10"%></li>
  <li class="name"><%= f.label :name, 'URL' %></li>
  <li><%= f.text_field :url, class: "hoge", size: "60x10" %></li>
  <li class="name"><%= f.label :name, 'メモ' %></li>
  <li><%= f.text_area :body, class: "hoge", size: "60x5" %></li>
  <!--ここまで-->
  
  
  <li class="name"><%= f.submit "リンク作成" ,class:"btn btn-secondary"%></li>
</ul>

<% end %>

</div>

app/views/links/edit.html.erb
<%= render "layouts/header2" %>
<main>
   <div class="row main">
      <%= render 'links/form', link: @link%>
   </div>
</main>

app/views/links/index.html.erb
<%= render "layouts/header" %>
<main class="link-main">
   <% @links.each do |link| %>
   <div class="box" style="border: solid 2px">
      <ul>
         <li><a href="<%= link.url %>"><%= link.title %></a></li>
         <li><%= link.body %></li>
          <%= tag.color %>
         <li class="delete"> <%= link_to "編集", edit_link_path(link), style:"font-size:10px; color:green;"%></li>
         <li class="delete"> <%= link_to "削除", link_path(link),  method: :delete ,data: { confirm: "本当に消しますか？" },style:"font-size:10px; color:red;"%></li>
   </div>
   <% end %>
      </ul>
</main>

app/views/links/link.js.erb
<!--id="comments_areaにをrenderで指定した部分テンプレートに更新-->
$('colortag_<%= linktag.color %>').html("<%= j(render 'links/form', link: @link, linktag: @linktag) %>");
<!--フォームを送信したあとにフォームの値を空にします-->
$('colortag_<%= linktag.color %>').val('');

app/views/links/new.html.erb
<%= render "layouts/header2" %>
<main>
   <div class="row main">
      <%= render 'links/form', link: @link, linktag: @linktag %>
   </div>
</main>