config/routes.rb
Rails.application.routes.draw do
  get 'tags/create'
  root to: 'homes#toppage'
  devise_for :users
  resources :link_tags
  resources :tags
  resources :links
  resources :users
  post 'users/:id/edit' => 'users#update'
  post 'tags/first_create' => 'tags#first_create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/link.rb
class Link < ApplicationRecord
     belongs_to :user
     has_many :link_tags
     
     validates :title, presence: true
     validates :url, presence: true
     
end

app/models/link_tag.rb
class LinkTag < ApplicationRecord
    belongs_to :link
    belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :link_tags
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable       
  has_many :links, dependent: :destroy
  has_many :tags
  has_one_attached :image

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!, except: [:top]
    before_action :configure_permitted_parameters, if: :devise_controller?
    before_action :authenticate_user!
    before_action :set_host

    def after_sign_up_path_for(resource)
      tags_first_create_path(resource)
    end
    
    def after_sign_in_path_for(resource)
      links_path
    end
    
     private

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up,keys:[:email]) # 注目
    end
    
    def set_host
      Rails.application.routes.default_url_options[:host] = request.host_with_port
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
    def toppage
    end    
end

app/controllers/link_tags_controller.rb
class LinkTagsController < ApplicationController
  def create
    @link = Link.find(params[:id])
    linktag = current_user.linktags.new(link_id: @link.id)
    linktag.save
    render :link
  end

  def destroy
    @link = Link.find(params[:id])
    linktag = current_user.linktags.new(link_id: @link.id)
    linktag.destroy
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController


    def new
      @link = Link.new
      @linktag = LinkTag.new
      @linktags = LinkTag.all
      @tag = Tag.new #タグをユーザーに持たせるか
      @tags = Tag.where(user_id: current_user)
     if params[:tag]
      Tag.create(name: params[:tag])
     end
    end
    
    def create
      @link = Link.new(link_params)
      @link.user_id = current_user.id
      if @link.save
      redirect_to links_path
      else
      render :new
      end
    end
    
    def edit
       @link = Link.find(params[:id])
    end
    
    def update
      @link = Link.find(params[:id])
      @link.user_id = current_user.id
      if @link.update(link_params)
      redirect_to links_path
      else
      render :edit
      end
    end
    
    def index
       @links = Link.all.where(user_id: current_user)
    end
    
    def destroy
       link=Link.find(params[:id])
       link.destroy
       redirect_to links_path
    end 
    
  private

    def link_params
      params.require(:link).permit(:title,:url,:body,:color)
    end

    
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def create
    @tag = Tag.new(tag_params)
    @tag.save
  end

  def first_create(resourse)
    @tag = Tag.new(user_id: resource.id,name: "all")
    @tag.save
    redirect_to links_path
  end

  private
  def tag_params
    params.require(:tag).permit(:name)
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def index 
      @user = User.find(params[:id])
      @userinfo = current_user.id
    end

    def edit
      @user = User.find(params[:id])
    end

    def update
    user = User.find(params[:id])
    user.update(user_params)
    redirect_to user_path(user.id)  
    end

private
  def user_params
    params.require(:user).permit(:name, :email, :image)  
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/link_tags_helper.rb
module LinkTagsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header class="container-fluid bg-light w-100">
    <div class="row">
        <div class="header col-5">
          <%= link_to links_path do %>
          <%= image_tag 'pelinkcan.png' %>
          <% end %>
        </div>
        <div class="header col-4">
          <%= link_to new_link_path do %>
          <button type="button" class="btn btn-info">リンク作成</button>
        </div>
          <%end%>
        <div class="header col-1">
          <%= link_to user_path(current_user),style:"color:grey;" do%>
            <i class="far fa-user"></i> User
          <%end%>
        </div>
        <div class="header col-2">
          <%= link_to destroy_user_session_path,style:"color:grey;", method: :delete do %>
             <i class="fas fa-sign-out-alt"></i>LogOut
          <%end%>
        </div>
    </div>
</header>

app/views/layouts/_header2.html.erb
<header class="container-fluid bg-light w-100">
    <div class="row">
        <div class="header col-9">
          <%= link_to links_path do %>
          <%= image_tag 'pelinkcan.png' %>
          <% end %>
        </div>
        <div class="header col-1">
          <%= link_to user_path(current_user),style:"color:grey;" do%>
            <i class="far fa-user"></i> User
          <%end%>
        </div>
        <div class="header col-2">
          <%= link_to destroy_user_session_path,style:"color:grey;", method: :delete do %>
             <i class="fas fa-sign-out-alt"></i>Logout
          <%end%>
        </div>
    </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Pelinkcan</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <script src="https://kit.fontawesome.com/050c0d807d.js" crossorigin="anonymous"></script>
</head>

<body>
  <%= yield %>
</body>

</html>